/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnitest3_MyNdkTest */

#ifndef _Included_com_study_jnitest3_MyNdkTest
#define _Included_com_study_jnitest3_MyNdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnitest3_MyNdkTest
 * Method:    nativeCalc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_study_jnitest3_MyNdkTest_nativeCalc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
