/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gikimi_jni2_JniTest2 */

#ifndef _Included_com_gikimi_jni2_JniTest2
#define _Included_com_gikimi_jni2_JniTest2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gikimi_jni2_JniTest2
 * Method:    show1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gikimi_jni2_JniTest2_show1
  (JNIEnv *, jobject);

/*
 * Class:     com_gikimi_jni2_JniTest2
 * Method:    show2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gikimi_jni2_JniTest2_show2
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gikimi_jni2_JniTest2
 * Method:    show3
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_gikimi_jni2_JniTest2_show3
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_gikimi_jni2_JniTest2
 * Method:    show4
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_gikimi_jni2_JniTest2_show4
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_gikimi_jni2_JniTest2
 * Method:    show5
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_gikimi_jni2_JniTest2_show5
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     com_gikimi_jni2_JniTest2
 * Method:    show6
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gikimi_jni2_JniTest2_show6__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gikimi_jni2_JniTest2
 * Method:    show6
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gikimi_jni2_JniTest2_show6__
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
