/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest1 */

#ifndef _Included_JniTest1
#define _Included_JniTest1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniTest1
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniTest1_printHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
